# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-07 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
                ('timezone_now', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_utcnow', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('datetime_now', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
